dependencies:
  - openzeppelin/openzeppelin-contracts@4.7.2

compiler:
  solc:
    remappings:
      - '@openzeppelin=openzeppelin/openzeppelin-contracts@4.7.2'

dotenv: .env
networks:
  default: development
  development:
    verify: False
  rinkeby:
    verify: True

wallets:
  from_key: ${PRIVATE_KEY}